{
  "data": {
      "id": 12,
      "invoice_year": "25-26",
      "company_id": 1,
      "branch_short": "CSEI",
      "branch_name": "CAPSTONE EXPORT & IMPORT",
      "invoice_no": 7,
      "invoice_ref": "CSEI\/TESTERAGILE25-267",
      "invoice_date": "2026-01-08",
      "invoice_buyer_id": 22,
      "invoice_buyer": "AGILE",
      "invoice_consignee_id": 22,
      "invoice_consignee": "AGILE",
      "invoice_destination_port": "DUNDEE",
      "invoice_destination_country": "AUSTRALIA",
      "invoice_status": "Order in Hand",
      "contract_date": "2026-01-03",
      "contract_ref": "CSEI\/TESTERAGILE\/25-26\/2",
      "contract_pono": "CSEI\/TESTERAGILE\/25-26\/2",
      "invoice_buyer_add": "Street Name:381 Greenholt Court\nCity:Port Aniya\nState:Nevada\nZip Code:51046\nCountry:USA",
      "invoice_consignee_add": "Street Name:381 Greenholt Court\nCity:Port Aniya\nState:Nevada\nZip Code:51046\nCountry:USA",
      "invoice_container_size": "3 X 40FT FCL",
      "invoice_loading": "CHENNAI",
      "invoice_discharge": "DUNDEE",
      "invoice_cif": "DUNDEE",
      "invoice_payment_terms": "lc AT sight",
      "invoice_remarks": "dfdfdf",
      "invoice_consig_bank": null,
      "invoice_consig_bank_address": null,
      "invoice_prereceipts": "GUNTUR",
      "invoice_precarriage": "AIR",
      "invoice_vessel_flight_no": "vessel",
      "invoice_dollar_rate": "34.00",
      "invoice_product": "CHILLY",
      "invoice_product_cust_des": "des",
      "invoice_gr_code": "CHILLY",
      "invoice_lut_code": "NEL",
      "invoice_bl_no": null,
      "invoice_bl_date": null,
      "invoice_sb_no": null,
      "invoice_sb_date": null,
      "invoice_container": null,
      "invoice_voyage": null,
      "invoice_vessel": null,
      "invoice_seal": null,
      "invoice_shipper": null,
      "invoice_etd_date": null,
      "invoice_eta_date": null,
      "invoice_i_value_usd": null,
      "invoice_i_value_inr": null,
      "invoice_fob_usd": null,
      "invoice_fob_inr": null,
      "invoice_insurance": null,
      "invoice_freight": null,
      "invoice_exch_rate": null,
      "invoice_let_exports_date": null,
      "invoice_dd_scroll_no": null,
      "invoice_dd_date": null,
      "invoice_dd_status": "Pending",
      "invoice_default_statement": "WE INTEND TO CLAIM RoDTEP SCHEME-RoDTEP Entry No.683 @ 1%",
      "invoice_rodtep_per": 0.0200000000000000004163336342344337026588618755340576171875,
      "invoice_drawback_per": 0.01000000000000000020816681711721685132943093776702880859375,
      "created_by": "superadmins",
      "created_at": "2026-01-08T06:53:15.000000Z",
      "updated_at": "2026-01-08T06:53:35.000000Z",
      "updated_by": "superadmins",
      "subs": [
          {
              "id": 9,
              "invoiceSub_ref": "CSEI\/TESTERAGILE25-267",
              "invoiceSub_item_id": 4,
              "purchase_sub_id": 4,
              "invoiceSub_qnty": "2.00",
              "invoiceSub_mrp": "2333.00",
              "invoiceSub_selling_rate": "2335.00",
              "invoiceSub_item_gst": "12.00",
              "invoiceSub_batch_no": "4",
              "invoiceSub_manufacture_date": "2026-01-01",
              "invoiceSub_expire_date": "2026-02-08",
              "item_hsn_code": "30049079",
              "item_brand_name": "ANOVATE CREAM (20GM)",
              "item_generic_name": "LIDOCAINE 2.5%W\/W + PHENYEPHRINE 0.1%W\/W + BECLOMETHASONE 0.025%W\/W",
              "item_company_name": "USV LTD"
          },
  
          {
              "id": 10,
              "invoiceSub_ref": "CSEI\/TESTERAGILE25-267",
              "invoiceSub_item_id": 4,
              "purchase_sub_id": 4,
              "invoiceSub_qnty": "8.00",
              "invoiceSub_mrp": "2333.00",
              "invoiceSub_selling_rate": "2335.00",
              "invoiceSub_item_gst": "12.00",
              "invoiceSub_batch_no": "4",
              "invoiceSub_manufacture_date": "2026-01-01",
              "invoiceSub_expire_date": "2026-02-08",
              "item_hsn_code": "30049079",
              "item_brand_name": "ANOVATE CREAM (20GM)",
              "item_generic_name": "LIDOCAINE 2.5%W\/W + PHENYEPHRINE 0.1%W\/W + BECLOMETHASONE 0.025%W\/W",
              "item_company_name": "USV LTD"
          }
      ]
  }
}