subs1[
  (invoicePackingSub_ref,
  invoicePackingSub_carton_no,
  invoicePackingSub_box_size,
  invoicePackingSub_item_id,
  invoicePackingSub_batch_no,
  invoicePackingSub_manufacture_date,
  invoicePackingSub_expire_date,
  invoicePackingSub_qnty,
  invoicePackingSub_mrp,
  invoicePackingSub_item_gst,
  invoicePackingSub_net_weight,
  invoicePackingSub_gross_weight)
];
